version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY:-gcr.io/make-automation-455521}/${DOCKER_IMAGE:-spotyme-backend}:${VERSION:-latest}
    container_name: spotyme-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Server Configuration
      PORT: 3000
      NODE_ENV: production
      
      # MongoDB Configuration
      MONGODB_URI: ${MONGODB_URI}
      
      # Spotify API Credentials
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      
      # Session Configuration
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_STORE_SECRET: ${SESSION_STORE_SECRET}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY:-7d}
      
      # Frontend URL (for CORS)
      FRONTEND_URL: ${FRONTEND_URL}
      
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      # Encryption Configuration
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      
      # Redis Configuration
      REDIS_URL: redis://:${REDIS_PASSWORD:-spotyme_redis_secure_pass_2024}@redis:6379
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - spotyme-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  mongodb:
    image: mongo:7.0
    container_name: spotyme-mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"  # Only bind to localhost in production
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-spotyme}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-backup:/backup  # Add backup volume
    networks:
      - spotyme-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
    command: ["--auth", "--bind_ip_all"]  # Enable authentication and bind to all IPs

  redis:
    image: redis:7-alpine
    container_name: spotyme-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"  # Only bind to localhost in production
    command: redis-server --appendonly yes --appendfsync everysec --requirepass ${REDIS_PASSWORD:-spotyme_redis_secure_pass_2024}
    volumes:
      - redis-data:/data
    networks:
      - spotyme-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  mongo-data:
    driver: local
  mongo-backup:
    driver: local
  redis-data:
    driver: local

networks:
  spotyme-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16